import { Pool } from 'pg';
import { quoteIdentifier, quoteLiteral } from './helpers';

const tableComments: Record<string, string> = {
  users: '终端用户主表',
  auth_identities: '用户认证身份绑定表',
  auth_verification_codes: '短信验证码表',
  admin_users: '运维中台管理员账号表',
  homes: '家庭主表',
  device_inventory: '设备库存与二维码池',
  devices: '已绑定设备主表与最新状态快照',
  home_members: '家庭成员关系表',
  home_device_links: '家庭与设备关联表',
  device_shares: '设备共享关系表',
  operation_logs: '终端侧操作日志表',
  device_binding_events: '设备绑定审计事件表',
  alerts: '运维告警事件表',
  command_audit: '控制指令审计表',
  config_templates: '通知模板配置表',
  alert_rules: '告警规则配置表',
  risk_rules: '风控规则配置表',
  mall_page_contents: '商城页面内容表',
  merchant_page_contents: '推广入驻页面内容表',
  merchant_applications: '商户入驻申请表',
  merchant_profiles: '商户档案表',
};

const columnComments: Record<string, Record<string, string>> = {
  users: {
    id: '用户主键',
    short_uid: '对外展示的短 UID',
    email: '历史邮箱字段',
    display_name: '用户显示名称',
    password_hash: '历史密码哈希',
    primary_email: '主邮箱',
    primary_phone: '主手机号',
    photo_url: '头像地址',
    status: '账号状态',
    wechat_openid: '微信小程序 openid',
    wechat_unionid: '微信 unionid',
    created_at: '创建时间',
    updated_at: '更新时间',
  },
  auth_identities: {
    id: '身份记录主键',
    user_pk: '所属用户主键',
    provider: '身份提供方',
    provider_user_id: '提供方用户标识',
    provider_app_id: '提供方应用标识',
    union_id: '跨应用联合标识',
    password_hash: '密码哈希',
    is_verified: '是否已验证',
    is_primary: '是否主身份',
    meta: '提供方附加信息',
    last_login_at: '最近登录时间',
    created_at: '创建时间',
    updated_at: '更新时间',
  },
  auth_verification_codes: {
    id: '验证码主键',
    target_type: '目标类型',
    target_value: '目标值',
    purpose: '用途',
    code_hash: '验证码哈希',
    expires_at: '过期时间',
    used_at: '使用时间',
    created_at: '创建时间',
  },
  admin_users: {
    id: '管理员主键',
    username: '登录账号',
    password_hash: '密码哈希',
    display_name: '显示名称',
    role: '角色',
    status: '账号状态',
    last_login_at: '最近登录时间',
    created_at: '创建时间',
    updated_at: '更新时间',
  },
  homes: {
    id: '家庭主键',
    name: '家庭名称',
    owner_id: '家庭所有者短 UID',
    created_at: '创建时间',
  },
  device_inventory: {
    id: '库存主键',
    qr_code: '设备二维码内容',
    serial_number: '设备序列号',
    product_model: '产品型号',
    firmware_version: '固件版本',
    status: '库存状态',
    created_at: '创建时间',
    updated_at: '更新时间',
  },
  devices: {
    id: '设备主键',
    name: '设备名称',
    owner_id: '设备所有者短 UID',
    inventory_id: '关联库存主键',
    serial_number: '设备序列号',
    location: '绑定时采集的位置快照',
    region_path: '标准化区域路径',
    is_on: '点火状态',
    fire_level: '火力档位',
    temp: '温度读数',
    gas: '燃气读数',
    smoke: '烟雾读数',
    flow: '流量读数',
    human_detected: '人体检测标记',
    vibration: '震动检测标记',
    locked: '是否锁定',
    valve_status: '阀门状态',
    last_heartbeat_at: '最近心跳时间',
    created_at: '创建时间',
    updated_at: '更新时间',
  },
  home_members: {
    home_id: '家庭主键',
    user_id: '成员短 UID',
    created_at: '创建时间',
  },
  home_device_links: {
    home_id: '家庭主键',
    device_id: '设备主键',
    created_at: '创建时间',
  },
  device_shares: {
    device_id: '设备主键',
    user_id: '被共享用户短 UID',
    created_at: '创建时间',
  },
  operation_logs: {
    id: '日志主键',
    stove_id: '设备主键',
    owner_id: '设备所有者短 UID',
    event: '事件内容',
    type: '日志类型',
    created_at: '创建时间',
  },
  device_binding_events: {
    id: '绑定事件主键',
    inventory_id: '库存主键',
    device_id: '设备主键',
    owner_id: '操作用户短 UID',
    event_type: '事件类型',
    detail: '事件详情',
    created_at: '创建时间',
  },
  alerts: {
    id: '告警主键',
    device_id: '设备主键',
    device_sn: '设备序列号快照',
    owner_uid: '设备所有者短 UID 快照',
    type: '告警类型',
    level: '告警级别',
    status: '处理状态',
    title: '告警标题',
    message: '告警内容',
    metric_key: '触发指标',
    current_value: '当前值',
    threshold_value: '阈值',
    handler_admin_id: '处理管理员主键',
    handler_comment: '处理备注',
    is_false_positive: '是否误报',
    triggered_at: '触发时间',
    resolved_at: '解除时间',
    detail: '告警详情',
    created_at: '创建时间',
    updated_at: '更新时间',
  },
  command_audit: {
    id: '审计主键',
    device_id: '设备主键',
    device_sn: '设备序列号快照',
    operator_type: '操作者类型',
    operator_admin_id: '管理员主键',
    operator_user_uid: '用户短 UID',
    operator_name: '操作者名称快照',
    command_type: '指令类型',
    request_payload: '请求载荷',
    response_payload: '响应载荷',
    status: '执行状态',
    failure_reason: '失败原因',
    started_at: '开始时间',
    finished_at: '结束时间',
    created_at: '创建时间',
  },
  config_templates: {
    id: '模板主键',
    name: '模板名称',
    template_type: '模板类型',
    title: '模板标题',
    content: '模板内容',
    channels: '投递渠道',
    variables: '变量列表',
    enabled: '是否启用',
    created_by: '创建管理员主键',
    updated_by: '更新管理员主键',
    created_at: '创建时间',
    updated_at: '更新时间',
  },
  alert_rules: {
    id: '规则主键',
    name: '规则名称',
    rule_key: '规则键',
    severity: '严重级别',
    enabled: '是否启用',
    metric_key: '指标键',
    expression: '表达式',
    actions: '动作列表',
    delay_seconds: '延迟秒数',
    scope: '作用范围',
    created_by: '创建管理员主键',
    updated_by: '更新管理员主键',
    created_at: '创建时间',
    updated_at: '更新时间',
  },
  risk_rules: {
    id: '规则主键',
    name: '规则名称',
    rule_key: '规则键',
    enabled: '是否启用',
    threshold_expression: '阈值表达式',
    action: '命中动作',
    duration_seconds: '持续秒数',
    reason: '风控原因',
    scope: '作用范围',
    created_by: '创建管理员主键',
    updated_by: '更新管理员主键',
    created_at: '创建时间',
    updated_at: '更新时间',
  },
  mall_page_contents: {
    id: '页面内容主键',
    page_key: '页面标识',
    version_type: '版本类型',
    title: '页面标题',
    payload: '页面内容 JSON',
    created_by: '创建管理员主键',
    updated_by: '更新管理员主键',
    published_by: '发布管理员主键',
    published_at: '发布时间',
    created_at: '创建时间',
    updated_at: '更新时间',
  },
  merchant_page_contents: {
    id: '页面内容主键',
    page_key: '页面标识',
    version_type: '版本类型',
    title: '页面标题',
    payload: '页面内容 JSON',
    created_by: '创建管理员主键',
    updated_by: '更新管理员主键',
    published_by: '发布管理员主键',
    published_at: '发布时间',
    created_at: '创建时间',
    updated_at: '更新时间',
  },
  merchant_applications: {
    id: '入驻申请主键',
    user_pk: '申请用户主键',
    status: '审核状态',
    level_code: '申请级别编码',
    merchant_name: '商户名称',
    contact_name: '联系人',
    contact_phone: '联系电话',
    region: '所在区域',
    address: '联系地址',
    note: '补充说明',
    snapshot: '提交快照',
    review_comment: '审核备注',
    reviewed_by: '审核管理员主键',
    reviewed_at: '审核时间',
    created_at: '创建时间',
    updated_at: '更新时间',
  },
  merchant_profiles: {
    id: '商户档案主键',
    application_id: '来源申请主键',
    user_pk: '所属用户主键',
    merchant_name: '商户名称',
    contact_name: '联系人',
    contact_phone: '联系电话',
    level_code: '商户级别编码',
    status: '商户状态',
    approved_by: '审批管理员主键',
    approved_at: '审批通过时间',
    created_at: '创建时间',
    updated_at: '更新时间',
  },
};

export async function applySchemaComments(mainPool: Pool) {
  for (const [table, comment] of Object.entries(tableComments)) {
    await mainPool.query(
      `COMMENT ON TABLE ${quoteIdentifier(table)} IS ${quoteLiteral(comment)}`
    );
  }

  for (const [table, columns] of Object.entries(columnComments)) {
    for (const [column, comment] of Object.entries(columns)) {
      await mainPool.query(
        `COMMENT ON COLUMN ${quoteIdentifier(table)}.${quoteIdentifier(column)} IS ${quoteLiteral(comment)}`
      );
    }
  }
}
