import { Pool } from 'pg';
import { quoteIdentifier, quoteLiteral } from './helpers';

const tableComments: Record<string, string> = {
  users: '终端用户主表。',
  auth_identities: '用户内外部身份绑定表。',
  auth_verification_codes: '认证流程使用的一次性验证码表。',
  admin_users: '运维中台管理员账号表。',
  homes: '用户家庭主表。',
  device_inventory: '设备库存与二维码绑定池。',
  devices: '已绑定设备主表及最新状态快照。',
  home_members: '家庭与用户成员关系表。',
  home_device_links: '家庭与设备关联关系表。',
  device_shares: '用户间设备分享关系表。',
  operation_logs: '用户侧设备操作与事件日志表。',
  device_binding_events: '设备绑定与解绑审计事件表。',
  alerts: '运维告警事件表。',
  command_audit: '指令执行审计表。',
  config_templates: '运维通知模板配置表。',
  alert_rules: '告警规则配置表。',
  risk_rules: '风控规则配置表。',
};

const columnComments: Record<string, Record<string, string>> = {
  users: {
    id: '用户主键。',
    short_uid: '产品流程对外暴露的短 UID。',
    email: '登录邮箱地址。',
    display_name: '用户显示名称。',
    password_hash: '邮箱登录密码哈希。',
    photo_url: '用户头像 URL。',
    created_at: '记录创建时间。',
    updated_at: '记录最后更新时间。',
    wechat_openid: '微信小程序 openid。',
    wechat_unionid: '跨应用的微信 unionid。',
    primary_email: '主邮箱地址。',
    primary_phone: '主手机号。',
    status: '用户账号状态。',
  },
  auth_identities: {
    id: '身份记录主键。',
    user_pk: '绑定的用户主键。',
    provider: '身份提供方编码。',
    provider_user_id: '提供方侧的唯一用户 ID。',
    provider_app_id: '提供方应用标识。',
    union_id: '跨应用的 union 标识。',
    password_hash: '可用时的提供方密码哈希。',
    is_verified: '该身份是否已完成验证。',
    is_primary: '该身份是否为主身份。',
    meta: '提供方元数据载荷。',
    last_login_at: '该身份最后登录时间。',
    created_at: '记录创建时间。',
    updated_at: '记录最后更新时间。',
  },
  auth_verification_codes: {
    id: '验证码主键。',
    target_type: '验证目标类型。',
    target_value: '验证目标值。',
    purpose: '验证码用途。',
    code_hash: '验证码哈希。',
    expires_at: '验证码过期时间。',
    used_at: '验证码被使用的时间。',
    created_at: '记录创建时间。',
  },
  admin_users: {
    id: '管理员主键。',
    username: '管理员登录用户名。',
    password_hash: '管理员密码哈希。',
    display_name: '管理员显示名称。',
    role: '管理员角色。',
    status: '管理员账号状态。',
    last_login_at: '最后登录时间。',
    created_at: '记录创建时间。',
    updated_at: '记录最后更新时间。',
  },
  homes: {
    id: '家庭主键。',
    name: '家庭名称。',
    owner_id: '家庭所有者短 UID。',
    created_at: '记录创建时间。',
  },
  device_inventory: {
    id: '库存主键。',
    qr_code: '设备二维码内容。',
    serial_number: '设备序列号。',
    product_model: '产品型号。',
    firmware_version: '库存记录中的固件版本。',
    status: '库存绑定状态。',
    created_at: '记录创建时间。',
    updated_at: '记录最后更新时间。',
  },
  devices: {
    id: '设备主键。',
    name: '用户自定义设备名称。',
    owner_id: '设备所有者短 UID。',
    location: '手机绑定时采集的安装位置快照。',
    is_on: '当前点火开关状态。',
    fire_level: '当前火力档位。',
    temp: '最新温度读数。',
    gas: '最新燃气读数。',
    smoke: '最新烟雾读数。',
    flow: '最新流量读数。',
    human_detected: '最新人体检测标记。',
    vibration: '最新震动检测标记。',
    created_at: '记录创建时间。',
    updated_at: '记录最后更新时间。',
    inventory_id: '关联的库存记录 ID。',
    serial_number: '设备序列号。',
    locked: '设备锁定状态。',
    valve_status: '阀门状态。',
    last_heartbeat_at: '设备最后心跳时间。',
    region_path: '用于筛选与聚合的标准化区域路径。',
  },
  home_members: {
    home_id: '家庭 ID。',
    user_id: '成员用户短 UID。',
    created_at: '记录创建时间。',
  },
  home_device_links: {
    home_id: '家庭 ID。',
    device_id: '设备 ID。',
    created_at: '记录创建时间。',
  },
  device_shares: {
    device_id: '被分享的设备 ID。',
    user_id: '接收分享的用户短 UID。',
    created_at: '记录创建时间。',
  },
  operation_logs: {
    id: '操作日志主键。',
    stove_id: '关联设备 ID。',
    owner_id: '设备所有者短 UID。',
    event: '日志事件文本。',
    type: '日志类型。',
    created_at: '记录创建时间。',
  },
  device_binding_events: {
    id: '绑定事件主键。',
    inventory_id: '库存 ID。',
    device_id: '绑定后的设备 ID，解绑等场景可为空。',
    owner_id: '执行绑定变更的用户短 UID。',
    event_type: '绑定事件类型。',
    detail: '绑定事件详情载荷。',
    created_at: '记录创建时间。',
  },
  alerts: {
    id: '告警主键。',
    device_id: '关联设备 ID。',
    device_sn: '设备序列号快照。',
    owner_uid: '设备所有者短 UID 快照。',
    type: '告警类型。',
    level: '告警严重级别。',
    status: '告警处理状态。',
    title: '告警标题。',
    message: '告警内容。',
    metric_key: '触发告警的指标键。',
    current_value: '当前指标值。',
    threshold_value: '规则阈值。',
    handler_admin_id: '处理该告警的管理员 ID。',
    handler_comment: '处理备注。',
    is_false_positive: '是否标记为误报。',
    triggered_at: '告警触发时间。',
    resolved_at: '告警解除时间。',
    detail: '告警详情载荷。',
    created_at: '记录创建时间。',
    updated_at: '记录最后更新时间。',
  },
  command_audit: {
    id: '指令审计主键。',
    device_id: '关联设备 ID。',
    device_sn: '设备序列号快照。',
    operator_type: '指令发起方类型。',
    operator_admin_id: '管理员操作者 ID。',
    operator_user_uid: '终端用户操作者短 UID。',
    operator_name: '操作人显示名称快照。',
    command_type: '指令类型。',
    request_payload: '指令请求载荷。',
    response_payload: '指令响应载荷。',
    status: '指令执行状态。',
    failure_reason: '执行失败原因。',
    started_at: '执行开始时间。',
    finished_at: '执行结束时间。',
    created_at: '记录创建时间。',
  },
  config_templates: {
    id: '模板主键。',
    name: '模板内部名称。',
    template_type: '模板类型。',
    title: '模板标题。',
    content: '模板内容主体。',
    channels: '投递渠道载荷。',
    variables: '支持变量载荷。',
    enabled: '模板是否启用。',
    created_by: '创建管理员 ID。',
    updated_by: '最后更新管理员 ID。',
    created_at: '记录创建时间。',
    updated_at: '记录最后更新时间。',
  },
  alert_rules: {
    id: '规则主键。',
    name: '告警规则名称。',
    rule_key: '稳定的告警规则键。',
    severity: '告警严重级别。',
    enabled: '规则是否启用。',
    metric_key: '目标指标键。',
    expression: '规则表达式。',
    actions: '规则动作列表载荷。',
    delay_seconds: '告警延迟秒数。',
    scope: '规则作用范围载荷。',
    created_by: '创建管理员 ID。',
    updated_by: '最后更新管理员 ID。',
    created_at: '记录创建时间。',
    updated_at: '记录最后更新时间。',
  },
  risk_rules: {
    id: '规则主键。',
    name: '风控规则名称。',
    rule_key: '稳定的风控规则键。',
    enabled: '规则是否启用。',
    threshold_expression: '风控阈值表达式。',
    action: '规则命中后执行的动作。',
    duration_seconds: '动作持续秒数。',
    reason: '风控原因。',
    scope: '规则作用范围载荷。',
    created_by: '创建管理员 ID。',
    updated_by: '最后更新管理员 ID。',
    created_at: '记录创建时间。',
    updated_at: '记录最后更新时间。',
  },
};

export async function applySchemaComments(mainPool: Pool) {
  for (const [table, comment] of Object.entries(tableComments)) {
    await mainPool.query(
      `COMMENT ON TABLE ${quoteIdentifier(table)} IS ${quoteLiteral(comment)}`
    );
  }

  for (const [table, columns] of Object.entries(columnComments)) {
    for (const [column, comment] of Object.entries(columns)) {
      await mainPool.query(
        `COMMENT ON COLUMN ${quoteIdentifier(table)}.${quoteIdentifier(column)} IS ${quoteLiteral(comment)}`
      );
    }
  }
}
